### ISSUE TITLE
Just so you're aware

### ISSUE THREAD

**Issue by HarbingerOfFire** [HarbingerOfFire/BivitattusDatabase#1]
@ScriptSlayer0
I'm going to be updating the code with this instead of HDF5, so hopefully this will solve our error. Do you want me to just take it over, or should I wait until you find our current error?

**Comment by ScriptSlayer0** [comment]
Today I have fixed it, the only thing is that now I have found a new problem, when you create a new database and it gives you the wrong password, it tries to decrypt the database but it corrupts it, at the moment I don't know how to do it, but maybe you can fix it.
